USE [TESTE]
GO
IF OBJECT_ID('DBO.P_CFOP_AGRUPADO') IS NOT NULL
BEGIN
    DROP PROCEDURE DBO.P_NOTA_FISCAL_ITEM
    IF OBJECT_ID('DBO.P_CFOP_AGRUPADO') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE DBO.P_CFOP_AGRUPADO>>>'
    ELSE
        PRINT '<<< PROCEDURE DBO.P_CFOP_AGRUPADO APAGADA >>>'
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 

CREATE PROCEDURE P_CFOP_AGRUPADO
AS
BEGIN

	SELECT CFOP, SUM(BASEICMS) as BASEICMS, SUM(VALORICMS) AS VALORICMS, SUM(BASEIPI) AS BASEIPI, SUM(VALORIPI) AS VALORIPI FROM NOTAFISCALITEM 
	GROUP BY CFOP

END
GO
GRANT EXECUTE ON DBO.P_NOTA_FISCAL_ITEM TO [PUBLIC]
GO
IF OBJECT_ID('DBO.P_CFOP_AGRUPADO') IS NOT NULL
    PRINT '<<< PROCEDURE DBO.P_CFOP_AGRUPADO CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE DBO.P_CFOP_AGRUPADO >>>'
GO